---
title: "Final Project"
author: "Laura Federline"
date: "December 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
demographic <- read.csv("~/2019 Fall Semester/ST442/Final Prject/demographic.csv", header=TRUE)
questionnaire <- read.csv("~/2019 Fall Semester/ST442/Final Prject/questionnaire.csv", header=TRUE)
```

```{r include=FALSE}
#Packages
library(dplyr)
library(rpart)
library(partykit)
library(rattle)
library(caret)
library(e1071)
```

```{r}
#Subsetting datasets and renaming variables
demo_orig_vars <- c("SEQN","RIAGENDR","RIDAGEYR","RIDRETH1","DMDCITZN","DMDEDUC2","DMDMARTL","DMDHHSIZ","INDHHIN2")
demo_subset <- demographic[demo_orig_vars]
demo_rename_vars <- c("SEQN","gender","age","race","citizenship","adult_education","marital_status","number_household","HH_income")
names(demo_subset) <- demo_rename_vars

q_orig_vars <- c("SEQN","BPQ020","BPQ080","MCQ010","MCQ080","MCQ082","MCQ160F","MCQ220","ALQ101","CBD070","DIQ010","DBQ700","DBD895","FSD032A","HIQ011","HUQ010","IND235","DPQ020","PAQ665","SLD010H","SMQ020","WHQ030","DLQ040","HUQ020")
q_subset <- questionnaire[q_orig_vars]
q_rename_vars <- c("SEQN","hypertension","high_cholesterol","asthma","overweight","celiac","stroke","cancer","alcohol","groceries","diabetes","diet","meals_out","food_insecurity","insurance","general_health","monthly_income","feel_depressed","moderate_activity","sleep_hours","smoked","weight_status","difficulty_concentrating","health_compared_1year")
names(q_subset) <- q_rename_vars
varlist <- data.frame(q_orig_vars,q_rename_vars)
varlist
```

```{r}
#Merging Datasets
data <- merge(demo_subset,q_subset,by="SEQN")
head(data)
```

```{r}

data_recode = filter(data, hypertension<7 & high_cholesterol<7 & asthma<7 & overweight<7 & celiac<7 & stroke<7 & cancer<7 & alcohol<7 & diabetes<7 & diet<7 & food_insecurity<7 & insurance<7 & general_health<7 & feel_depressed<7 & moderate_activity<7 & smoked<7 & weight_status<7 & difficulty_concentrating<7 & health_compared_1year <7 & HH_income != 77 & HH_income != 99 & sleep_hours < 76)

```


Classification Tree for Cancer
```{r}
#Exclude other response variables
cancer_list <- c("SEQN","high_cholesterol","diabetes")
data_cancer <- select(data_recode,-cancer_list) %>% na.omit()


n <- nrow(data_cancer)
m <- floor(n*.75)
index <- sample(n,m,replace=FALSE)

#train_cancer <- data_cancer[index,]
#test_cancer <- data_cancer[-index,]
#cancer_fit <- rpart(factor(cancer) ~ ., data=train, control=rpart.control(minbucket=20))
#plot(as.party(cancer_fit))
#fancyRpartPlot(cancer_fit)
#names(test)
#test_y_predict <- predict(cancer_fit,test[,-14],type="vector")
#table(test_y_predict,factor(test$cancer))
#table <- table(test_y_predict,test$cancer)


DATA_tree_cancer <- train(factor(cancer) ~ age+gender+hypertension, method = "rpart", data = data_cancer, trControl = trainControl(method = "cv"))
fancyRpartPlot(DATA_tree_cancer$finalModel, sub = "")
confusionMatrix(DATA_tree_cancer)

```

```{r}
#Decision Tree for Diabetes
diabetes_list <- c("SEQN","high_cholesterol","cancer")
data_diabetes <- select(data_recode,-diabetes_list) %>% na.omit()

DATA_tree_diabetes <- train(factor(diabetes) ~ . , method = "rpart", data = data_diabetes, trControl = trainControl(method = "cv"))
fancyRpartPlot(DATA_tree_diabetes$finalModel, sub = "")
confusionMatrix(DATA_tree_diabetes)
```

```{r}
#Decision Tree for High Cholesterol
cholesterol_list <- c("SEQN","diabetes","cancer")
data_cholesterol <- select(data_recode,-cholesterol_list) %>% na.omit()

DATA_tree_cholesterol <- train(factor(high_cholesterol) ~ . , method = "rpart", data = data_cholesterol, trControl = trainControl(method = "cv"))
fancyRpartPlot(DATA_tree_cholesterol$finalModel, sub = "")
confusionMatrix(DATA_tree_cholesterol)
```

